on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - name: modprobe
      run: sudo apt update -y && sudo apt install -y linux-image-generic && lsmod
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build docker images
      run: docker build -t local -f .devcontainer/Dockerfile .
    - name: Run tests
      run: |
        modprobe gpio-sim &&
        docker run -v $GITHUB_WORKSPACE:/workdir -w/workdir \
        --mount type=bind,source=/sys,target=/sys \
        --mount type=bind,source=/dev,target=/dev \
        --privileged -P --cap-add=SYS_ADMIN \
        local ./setup.sh
