on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build docker images
      run: docker build -t local -f .devcontainer/Dockerfile .
    - name: Run tests
      run: |
        docker run -v $GITHUB_WORKSPACE:/workdir -w/workdir \
        --mount type=bind,source=/sys,target=/sys \
        --mount type=bind,source=/dev,target=/dev \
        --privileged -P --cap-add=SYS_ADMIN \
        local ./setup
